Dockerfile
api/flight_blender_api.postman_collection.json
auth_helper/dss_auth_helper.py
auth_helper/utils.py
docker-compose.yml
flight_blender/urls.py
rid_operations/dss_rid_helper.py
rid_operations/rid_utils.py
rid_operations/tasks.py
rid_operations/views.py
uss_operations/views.py

This PR makes changes to the Blender infrastructure to accommodate creation of ISA and notifications

RID Qualifier: Rid isa creation

---

api/flight-blender-1.0.0-resolved.yaml
importers/import_flight_json_blender_local.py
importers/rid_sample_data.py
importers/rid_samples/flight_1_rid_aircraft_state.json
rid_operations/rid_utils.py
rid_operations/tasks.py
rid_operations/views.py

This code updates the RID import data fields

Rid import branch

---

docker-compose.yml
flight_blender/settings.py
flight_feed_operations/tasks.py
requirements.txt
rid_operations/rid_utils.py
rid_operations/tasks.py
rid_operations/views.py
uss_operations/views.py

This PR refactors the flight stream operation tasks to use Redis Sorted set commands. These are applied to process RID streaming data. This enables a more robust qualification process and updated logging / debugging mechanism.

Rid qualifier backend update

---

docker-compose.yml
flight_blender/settings.py
flight_feed_operations/apps.py
flight_feed_operations/flight_stream_helper.py
flight_feed_operations/management/commands/create_default_consumer_group.py
flight_feed_operations/tasks.py
requirements.txt
rid_operations/tasks.py
rid_operations/views.py

This PR removes the push to spotlight mechanism and removes the necessity to use / have Celery Beat since that was the main way to push flight data in Blender.

Removing push to spotlight

---

flight_feed_operations/flight_stream_helper.py
flight_feed_operations/tasks.py

This PR removes code that pushed Opensky Network data into Flight Spotlight

Removing push to spotlight for flight observations

---

deployment_support/README.md
flight_declaration_operations/tasks.py
flight_declaration_operations/views.py
notification_operations/data_definitions.py
requirements.txt
rid_operations/views.py
scd_operations/opint_helper.py

This PR adds notifications to inform re changes to the Declaration status.

Flight declaration notifications

---

api/flight-blender-1.0.0-resolved.yaml
api/flight_blender_api.postman_collection.json
rid_operations/rid_utils.py
rid_operations/urls.py
rid_operations/views.py

Adding a capabilities endpoint for RID

Add RID capabilities endpoint + documentation

---

api/flight-blender-1.0.0-resolved.yaml
flight_declaration_operations/data_definitions.py
flight_declaration_operations/views.py

This PR updates the return response object on successful flight declaration creation. API documentation is also updated.

Declaration endpoint update

---

importers/ietf-drip/auth_decoder.py
importers/ietf-drip/basic_id_decoder.py
importers/ietf-drip/drip_messages.py
importers/ietf-drip/import-drip-decoder.py
importers/ietf-drip/location_decoder.py
importers/ietf-drip/operator_id_decoder.py
importers/ietf-drip/self_id_decoder.py
importers/ietf-drip/system_decoder.py

Add support for decoding Drone Remote ID Protocol (drip) messages using ASTM F3411 specifications.
**To Do:** Comments and Docstrings
**Uses:**  python3 importers/ietf-drip/import-drip-decoder.py '/opt/rid-test-vectors'
DRIP_MESSAGE_BASIC_ID
UAType: 1
IDType: 2
UASID: b'16488DJ1P4001'
*********************
++++++++++++++++++++++++++++++++++++++++
DRIP_MESSAGE_LOCATION
Status: 0
HeightType: 0
Direction: 0.0
SpeedHorizontal: 0.0
SpeedVertical: 0.0
Latitude: 0.0
Longitude: 0.0
AltitudeBaro: 20050.0
AltitudeGeo: -1000.0
Height: -1000.0
Timestamp: 1077.0
HorizAccuracy: 1
VertAccuracy: 150
SpeedAccuracy: 10
BaroAccuracy: 150
TSAccuracy: 3
*********************
++++++++++++++++++++++++++++++++++++++++
DRIP_MESSAGE_AUTH
AuthPage:-1
AuthData (hex): 0x22 0x50 0x6 0x89 0x95 0x23 0x2e 0x7 0x4 0x20 …

Drip itef decoder

---

.env.sample
conformance_monitoring_operations/conformance_checks_handler.py
conformance_monitoring_operations/custom_signals.py
deployment_support/README.md
flight_declaration_operations/views.py

This PR adds a new environmental variable to turn on / off DSS interactions for conformance monitoring and flight declarations

Conformance monitoring conditional dss updates

---

api/flight-blender-1.0.0-resolved.yaml

When running blender locally, I noticed a disparity between openapi data description and what was actually received. Here's a change to reflect those disparities.

update openapi schema according to reveiced data

---

api/flight-blender-1.0.0-resolved.yaml

Adds pagination url params to flight declarations and geofences

add pagination params

---

flight_feed_operations/admin.py
flight_feed_operations/models.py
flight_feed_operations/views.py
importers/submit_signed_telemetry.py

Added verification of signed responses in importers directory

Signed message response verification

---

auth_helper/dss_auth_helper.py
flight_feed_operations/flight_stream_helper.py
flight_feed_operations/rid_telemetry_helper.py
flight_feed_operations/views.py
rid_operations/dss_rid_helper.py
rid_operations/rid_utils.py
rid_operations/tasks.py
rid_operations/urls.py
rid_operations/view_port_ops.py
rid_operations/views.py
uss_operations/urls.py
uss_operations/uss_data_definitions.py
uss_operations/views.py

Updated to fix v22 of RID spec

Rid qualifier updates

---

common/database_operations.py
flight_declaration_operations/models.py
flight_declaration_operations/tasks.py
flight_declaration_operations/views.py
requirements.txt
scd_operations/dss_scd_helper.py

This PR 
- removes some redundant calls for declaration update 
- updates celery version
- Adds flight authorization object in flight declaration creation view
- updates typo when parsing DSS opint creation response

Declaration creation refactor

---

flight_declaration_operations/tasks.py
scd_operations/dss_scd_helper.py
scd_operations/opint_helper.py

This PR catches additional responses from the DSS during operational intent creation and also updates the corresponding operational state

Refactor DSS operational intent creation

---

api/flight-blender-1.0.0-resolved.yaml
geo_fence_operations/common.py
geo_fence_operations/tasks.py

This PR updates the API definition and re-factors the Geozone processing in Blender as function

Geozone API fixes

---

auth_helper/utils.py
rid_operations/dss_rid_helper.py
rid_operations/tasks.py

This PR fixes the code base so that Flight Blender passes the RID Qualifier tests for ASTM NET RID v22

Updated to fix tests for flight details

---

common/database_operations.py
flight_declaration_operations/tasks.py

This PR fixes typing in database operations and solves the codespell errors

Fixed typing

---

common/data_definitions.py
docker-compose.yml
flight_declaration_operations/views.py
scd_operations/dss_scd_helper.py
scd_operations/flight_planning_data_definitions.py
scd_operations/scd_data_definitions.py
scd_operations/scd_test_harness_helper.py
scd_operations/urls.py
scd_operations/utils.py
scd_operations/views.py
uss_operations/uss_data_definitions.py
uss_operations/views.py

This implementation passes the F3548 tests as of February 2024

Update to codebase to include the new Flight Planning API

---

auth_helper/dss_auth_helper.py
common/database_operations.py
scd_operations/dss_scd_helper.py
scd_operations/opint_helper.py
scd_operations/scd_test_harness_helper.py
scd_operations/urls.py
scd_operations/views.py

This PR makes updates to the interuss SCD test harness  to enable passing of the `f3548_self_contained` tests

July 2024 scd test harness updates

---

scd_operations/data_definitions.py
scd_operations/dss_scd_helper.py
scd_operations/flight_planning_data_definitions.py
scd_operations/scd_data_definitions.py
scd_operations/scd_test_harness_helper.py
scd_operations/urls.py
scd_operations/views.py
uss_operations/uss_data_definitions.py
uss_operations/views.py

This update enables us to pass the InterUSS SCD tests for July 2024

Uspace tests july 2024
